import React from 'react'

export default function DataPanel() {
  return (
    <div>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
      <p>DataPanel</p>
    </div>
  )
}
